-- Migration 032: Add mc_prob_underperforming column to port_state.
--
-- H1 rename support: run_monte_carlo's return value semantics are being
-- clarified from "prob_beating" (ambiguous) to "prob_underperforming"
-- (the probability the portfolio underperforms SPY, i.e. the guardian
-- signal). The existing mc_prob column is preserved unchanged for
-- back-compat during the transition; this additive column gives the
-- persisted name the correct meaning.
--
-- DUAL-WRITE: the persistence path writes BOTH mc_prob (legacy, unchanged)
-- AND mc_prob_underperforming (new, same value) so readers on either column
-- remain correct during the transition window. The value is identical —
-- only the name conveys the correct semantics.
--
-- Additive-first per project rule: NULLable + DEFAULT NULL, never destructive.
-- Pre-existing port_state rows get NULL; write_port_state populates the column
-- via _PORT_STATE_COLUMNS on the next write cycle.
--
-- Idempotent: ALTER TABLE ADD COLUMN is wrapped in the schema_migrations
-- tracker so run_migrations() skips on re-run. The "duplicate column name"
-- branch in run_migrations() handles a fresh DB upgraded by init_db() if
-- port_state is ever promoted to a CREATE TABLE IF NOT EXISTS block there.
--
-- Target table: port_state in alphabot_state.db
-- Predecessor: 031_shadow_history_sym_ts_index.sql
--
-- Apply via:
--   sqlite3 alphabot_state.db < migrations/032_mc_prob_underperforming.sql
--   (migrations 004 through 031 must be applied first)

ALTER TABLE port_state ADD COLUMN mc_prob_underperforming REAL DEFAULT NULL;
