"""
Property-based (hypothesis) tests for the mc-knn-exit-gate cluster.

These complement the golden-fixture tests with invariants that must hold across
a wide input space:

* AC-1 invariant — ``run_monte_carlo``'s ``prob_beating`` is always a finite
  probability in [0, 100] (or the AC-2 insufficient sentinel), for any
  sufficient history. The standardization fix must not let a feature, a
  zero-variance dimension, or an extreme query point push the output out of
  band or to NaN/Inf.
* AC-2 invariant — when ``compute_exit_confirmation`` receives the insufficient
  sentinel (``None``), the MC gate must NOT veto: an armed, not-triggered
  position whose magnitude condition is satisfied increments the below-stop
  count every tick and confirms after ``EXIT_CONFIRM_TICKS``. The protective
  stop is never disabled by missing MC data.
* AC-2 invariant (preservation) — a REAL ``prob_beating`` at or above
  ``MC_SANITY_THRESHOLD`` still vetoes the exit; the sentinel bypass must not
  weaken the genuine MC sanity gate.
* AC-3 invariant — ``derive_cycle_mc_seed`` is deterministic and total over the
  cycle_id string space.

All invariants are RED-verifiable against pre-fix code where applicable
(``compute_exit_confirmation(None, ...)`` currently raises ``TypeError``).

PA-18 / fixture-provenance
--------------------------
No producer-computed value is hardcoded. Inputs are generated by hypothesis;
assertions are pure invariants (range, finiteness, monotone counting,
determinism). Module constants (``MC_SANITY_THRESHOLD``, ``MAGNITUDE_FLOOR_PCT``,
``EXIT_CONFIRM_TICKS``, ``MC_MIN_HISTORY_DAYS``) are read from ``math_engine``.
"""

from __future__ import annotations

import math

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

import math_engine


# ---------------------------------------------------------------------------
# History builder for property tests
# ---------------------------------------------------------------------------

def _date_key(i: int) -> str:
    base_day = 1 + i
    month = 1 + (base_day - 1) // 28
    day = 1 + (base_day - 1) % 28
    return f"2024-{month:02d}-{day:02d}"


def _build_history(
    spy_returns: list[float], holding_returns: list[float]
) -> dict[str, dict[str, dict[str, float]]]:
    """Build a {date:{ticker:{daily_ret}}} history from parallel return lists."""
    return {
        _date_key(i): {
            "SPY": {"daily_ret": spy_returns[i]},
            "AAA": {"daily_ret": holding_returns[i]},
        }
        for i in range(len(spy_returns))
    }


# Realistic daily-return scale — SPY returns rarely exceed +/-15% in a day.
_daily_return = st.floats(
    min_value=-0.15, max_value=0.15, allow_nan=False, allow_infinity=False
)


# ---------------------------------------------------------------------------
# AC-1 — run_monte_carlo output is always a bounded probability or the sentinel
# ---------------------------------------------------------------------------

# Minimum raw history days for an ELIGIBLE-sufficient pool (team-lead Ruling 2):
# the sufficiency guard counts days remaining after the early-window exclusion,
# so raw history must be >= MC_MIN_HISTORY_DAYS + (MC_VOL_WINDOW_DAYS - 1).
_MIN_ELIGIBLE_SUFFICIENT_RAW_DAYS = (
    math_engine.MC_MIN_HISTORY_DAYS + (math_engine.MC_VOL_WINDOW_DAYS - 1)
)


@settings(max_examples=120, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(
    spy_returns=st.lists(
        _daily_return,
        min_size=_MIN_ELIGIBLE_SUFFICIENT_RAW_DAYS,
        max_size=_MIN_ELIGIBLE_SUFFICIENT_RAW_DAYS + 40,
    ),
    holding_offset=st.floats(
        min_value=-0.05, max_value=0.05, allow_nan=False, allow_infinity=False
    ),
    spy_today=st.floats(
        min_value=-15.0, max_value=15.0, allow_nan=False, allow_infinity=False
    ),
    # Seed range spans the full post-AC-3 64-bit space so the property also
    # exercises seeds > 2**31 (the pre-fix modulus) — the widened seed must not
    # break run_monte_carlo's RNG path.
    seed=st.integers(min_value=0, max_value=2**64 - 1),
)
def test_run_monte_carlo_output_is_bounded_probability_or_sentinel(
    spy_returns: list[float],
    holding_offset: float,
    spy_today: float,
    seed: int,
) -> None:
    """
    AC-1 + AC-3 invariant: for any ELIGIBLE-sufficient history, with any
    standardization applied and any 64-bit seed, run_monte_carlo returns a
    finite float in [0, 100] — a real probability. It must never return NaN,
    Inf, or a number outside [0, 100], and (because the history is
    eligible-sufficient) it must never return the insufficient sentinel.

    Eligible-sufficiency (Ruling 2): the sufficiency guard counts days remaining
    after the early-window exclusion, so the history strategy is sized at
    >= MC_MIN_HISTORY_DAYS + (MC_VOL_WINDOW_DAYS - 1) raw days — every generated
    history has >= MC_MIN_HISTORY_DAYS eligible days.

    The holding return is derived from the SPY return plus a fixed offset so the
    feature standardization is exercised across correlated and degenerate
    (near-zero-variance) inputs. The seed strategy spans the full post-AC-3
    64-bit space so a widened seed that overflows or is mishandled would surface
    here.
    """
    assume(len(spy_returns) >= _MIN_ELIGIBLE_SUFFICIENT_RAW_DAYS)
    holding_returns = [r + holding_offset for r in spy_returns]
    history = _build_history(spy_returns, holding_returns)
    holdings = [{"ticker": "AAA", "allocation": 1.0, "last_percent_change": 0.0}]

    result = math_engine.run_monte_carlo(
        holdings,
        history,
        spy_today,
        simulation_paths=500,
        neighbor_k=8,
        seed=seed,
    )

    if result is None:
        # The history is eligible-sufficient, so the insufficient sentinel
        # would itself be a defect — surface it with a clear message.
        pytest.fail(
            f"run_monte_carlo returned the insufficient sentinel for a history "
            f"of {len(spy_returns)} raw days "
            f"({len(spy_returns) - (math_engine.MC_VOL_WINDOW_DAYS - 1)} "
            f"eligible after the early-window exclusion, "
            f">= MC_MIN_HISTORY_DAYS = {math_engine.MC_MIN_HISTORY_DAYS}). An "
            f"eligible-sufficient history must produce a real probability."
        )
    assert math.isfinite(result), (
        f"run_monte_carlo returned non-finite {result!r}. spy_returns="
        f"{spy_returns!r}, spy_today={spy_today!r}, seed={seed!r}."
    )
    assert 0.0 <= result <= 100.0, (
        f"run_monte_carlo returned {result!r} outside [0, 100]. "
        f"prob_beating must always be a valid probability percentage."
    )


# ---------------------------------------------------------------------------
# AC-2 — the insufficient sentinel never vetoes the protective stop
# ---------------------------------------------------------------------------

@settings(max_examples=150, deadline=None)
@given(
    stop_trigger_level=st.floats(
        min_value=-20.0, max_value=20.0, allow_nan=False, allow_infinity=False
    ),
    extra_drop=st.floats(
        min_value=0.0, max_value=30.0, allow_nan=False, allow_infinity=False
    ),
    starting_count=st.integers(min_value=0, max_value=10),
)
def test_insufficient_sentinel_never_vetoes_protective_stop(
    stop_trigger_level: float,
    extra_drop: float,
    starting_count: int,
) -> None:
    """
    AC-2 invariant. When prob_beating is the insufficient sentinel (None), an
    armed, not-triggered position whose return is at or below
    ``stop_trigger_level - MAGNITUDE_FLOOR_PCT`` must have its below-stop count
    INCREMENTED on every qualifying tick — never reset. The MC sanity gate must
    not veto when the MC second opinion is unavailable.

    Driven for EXIT_CONFIRM_TICKS consecutive qualifying ticks, the trailing
    stop must confirm.

    RED against pre-fix code: compute_exit_confirmation(prob_beating=None, ...)
    currently raises TypeError.
    """
    # current_return is strictly below the magnitude floor so the magnitude
    # gate is unambiguously satisfied.
    current_return = (
        stop_trigger_level - math_engine.MAGNITUDE_FLOOR_PCT - extra_drop - 0.01
    )

    count = starting_count
    hit = False
    for _ in range(math_engine.EXIT_CONFIRM_TICKS):
        prev = count
        count, hit = math_engine.compute_exit_confirmation(
            armed=True,
            is_triggered=False,
            current_return=current_return,
            stop_trigger_level=stop_trigger_level,
            prob_beating=None,
            current_below_stop_count=count,
        )
        assert count == prev + 1, (
            f"With the insufficient sentinel (None) and the magnitude condition "
            f"satisfied, below_stop_count went {prev} -> {count}; expected "
            f"{prev + 1}. A non-increment means the sentinel was treated as an "
            f"MC veto — insufficient data must not disable the protective stop."
        )

    assert hit is True, (
        f"After EXIT_CONFIRM_TICKS ({math_engine.EXIT_CONFIRM_TICKS}) qualifying "
        f"ticks with the insufficient sentinel, the trailing stop did not "
        f"confirm (hit={hit!r}). The protective stop must fire on the "
        f"ticks-below-stop condition alone when MC is unavailable."
    )


@settings(max_examples=150, deadline=None)
@given(
    stop_trigger_level=st.floats(
        min_value=-20.0, max_value=20.0, allow_nan=False, allow_infinity=False
    ),
    extra_drop=st.floats(
        min_value=0.0, max_value=30.0, allow_nan=False, allow_infinity=False
    ),
    vetoing_prob=st.floats(
        min_value=60.0, max_value=100.0, allow_nan=False, allow_infinity=False
    ),
    starting_count=st.integers(min_value=0, max_value=10),
)
def test_real_high_prob_still_vetoes_after_sentinel_bypass(
    stop_trigger_level: float,
    extra_drop: float,
    vetoing_prob: float,
    starting_count: int,
) -> None:
    """
    AC-2 preservation invariant. The sentinel bypass must NOT weaken the genuine
    MC sanity gate. A REAL prob_beating at or above MC_SANITY_THRESHOLD must
    still veto the exit: even with the magnitude condition satisfied, the
    below-stop count resets to 0 and the stop does not confirm.

    This guards against an over-broad fix that makes any "high-ish" value
    bypass the gate. Only the distinct out-of-band sentinel bypasses; a real
    high probability is still a real MC opinion that vetoes.
    """
    assume(vetoing_prob >= math_engine.MC_SANITY_THRESHOLD)
    current_return = (
        stop_trigger_level - math_engine.MAGNITUDE_FLOOR_PCT - extra_drop - 0.01
    )

    new_count, hit = math_engine.compute_exit_confirmation(
        armed=True,
        is_triggered=False,
        current_return=current_return,
        stop_trigger_level=stop_trigger_level,
        prob_beating=vetoing_prob,
        current_below_stop_count=starting_count,
    )
    assert new_count == 0, (
        f"A real prob_beating of {vetoing_prob!r} (>= MC_SANITY_THRESHOLD "
        f"{math_engine.MC_SANITY_THRESHOLD}) did not veto the exit: "
        f"below_stop_count is {new_count}, expected 0. The MC sanity gate must "
        f"still reset the count for a genuine high-confidence MC opinion — only "
        f"the insufficient SENTINEL bypasses the gate."
    )
    assert hit is False, (
        f"A real vetoing prob_beating of {vetoing_prob!r} produced "
        f"is_trailing_stop_hit={hit!r}; expected False. The genuine MC veto "
        f"must still suppress the exit."
    )


# ---------------------------------------------------------------------------
# AC-3 — derive_cycle_mc_seed is deterministic and total
# ---------------------------------------------------------------------------

@settings(max_examples=200, deadline=None)
@given(
    cycle_id=st.text(
        alphabet=st.characters(min_codepoint=48, max_codepoint=122),
        min_size=1,
        max_size=24,
    )
)
def test_derive_cycle_mc_seed_is_deterministic_and_total(cycle_id: str) -> None:
    """
    AC-3 invariant. derive_cycle_mc_seed is a pure, total function over the
    cycle_id string space: it never raises, always returns an int, and returns
    the same seed for the same cycle_id. The widening to a 64-bit space must not
    introduce a non-deterministic or partial path.
    """
    seed_a = math_engine.derive_cycle_mc_seed(cycle_id)
    seed_b = math_engine.derive_cycle_mc_seed(cycle_id)
    assert seed_a == seed_b, (
        f"derive_cycle_mc_seed('{cycle_id}') returned {seed_a!r} then "
        f"{seed_b!r}. It must be deterministic."
    )
    assert isinstance(seed_a, int), (
        f"derive_cycle_mc_seed('{cycle_id}') returned "
        f"{type(seed_a).__name__}, expected int."
    )
    assert seed_a >= 0, (
        f"derive_cycle_mc_seed('{cycle_id}') returned a negative seed "
        f"{seed_a!r}; numpy default_rng / SeedSequence require a non-negative "
        f"integer."
    )
